language: php

matrix:
  include:
    - php: 5.4
      env: WP_VERSION=4.4.14 ES_VERSION=2.2.0
    - php: 5.4
      env: WP_VERSION=latest ES_VERSION=2.2.0
    - php: 5.6
      env: WP_VERSION=latest ES_VERSION=2.2.0
    - php: 7.2
      env: WP_VERSION=latest ES_VERSION=2.2.0
    - php: 5.6
      env: WP_VERSION=nightly ES_VERSION=2.2.0
    - php: 5.6
      env: WP_VERSION=latest ES_VERSION=2.1.2
    - php: 5.6
      env: WP_VERSION=latest ES_VERSION=2.0.2
  fast_finish: true

branches:
  only:
    - master

before_install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - curl -O -L https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-$ES_VERSION.deb && sudo dpkg -i --force-confnew elasticsearch-$ES_VERSION.deb
  - sudo service elasticsearch start
  - composer global require "phpunit/phpunit=4.8.*|5.7.*"
  - which phpunit
  - phpunit --version

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - find . -path ./vendor -prune -o -type "f" -iname "*.php" | xargs -L "1" php -l
  - phpunit
  - if [[ "$ES_VERSION" == "2.2.0" ]]; then phpunit -c multisite.xml; fi;
