language: php

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=4.3.3 ES_VERSION=2.2.0
    - php: 5.3
      env: WP_VERSION=latest ES_VERSION=2.2.0
    - php: 5.6
      env: WP_VERSION=latest ES_VERSION=2.2.0
    - php: 7.0
      env: WP_VERSION=latest ES_VERSION=2.2.0
    - php: 5.6
      env: WP_VERSION=nightly ES_VERSION=2.2.0
    - php: 5.6
      env: WP_VERSION=latest ES_VERSION=1.4.5
    - php: 5.6
      env: WP_VERSION=latest ES_VERSION=1.7.5
    - php: 5.6
      env: WP_VERSION=latest ES_VERSION=2.0.2
  fast_finish: true

branches:
  only:
    - master

before_install:
    - curl -O -L https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-$ES_VERSION.deb && sudo dpkg -i --force-confnew elasticsearch-$ES_VERSION.deb
    - sudo service elasticsearch start

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - sleep 5 # ensure ES is running

script:
  - find . -path ./vendor -prune -o -type "f" -iname "*.php" | xargs -L "1" php -l
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      phpunit
      if [[ "$ES_VERSION" == "2.2.0" ]]; then
        phpunit -c multisite.xml
      fi
    fi
