sudo: false

language: php

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=4.3.3
    - php: 5.3
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=nightly
  fast_finish: true

branches:
  only:
    - master

services:
    - elasticsearch

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - sleep 5 # ensure ES is running

script:
  - find . -path ./vendor -prune -o -type "f" -iname "*.php" | xargs -L "1" php -l
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      phpunit
      phpunit -c multisite.xml
    fi
