sudo: false

language: php

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

language: php

matrix:
  include:
    - php: 5.4
      env: WP_VERSION=4.4.14 ES_VERSION=2.2.0
    - php: 5.4
      env: WP_VERSION=latest ES_VERSION=2.2.0
    - php: 5.6
      env: WP_VERSION=latest ES_VERSION=2.2.0
    - php: 7.2
      env: WP_VERSION=latest ES_VERSION=2.2.0
    - php: 5.6
      env: WP_VERSION=nightly ES_VERSION=2.2.0
    - php: 5.6
      env: WP_VERSION=latest ES_VERSION=2.1.2
    - php: 5.6
      env: WP_VERSION=latest ES_VERSION=2.0.2
  fast_finish: true

branches:
  only:
    - master

env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle

install:
  - bash bin/install-es.sh $ES_VERSION

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require "phpunit/phpunit=4.8.*|5.7.*"
  - which phpunit
  - phpunit --version
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - curl localhost:9200 && echo "ES is up" || (cat /tmp/elasticsearch.log && exit 1)

script:
  - find . -path ./vendor -prune -o -type "f" -iname "*.php" | xargs -L "1" php -l
  - phpunit
  - if [[ "$ES_VERSION" == "2.2.0" ]]; then phpunit -c multisite.xml; fi;

after_script:
  - cat /tmp/elasticsearch.log
