language: php

env:
    - ES_VERSION=2.2.0
    - ES_VERSION=1.7.5

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=4.3.3
    - php: 5.3
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=nightly
  fast_finish: true

branches:
  only:
    - master

before_install:
    - curl -O https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-$ES_VERSION.deb && sudo dpkg -i --force-confnew elasticsearch-$ES_VERSION.deb

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - sleep 5 # ensure ES is running

script:
  - find . -path ./vendor -prune -o -type "f" -iname "*.php" | xargs -L "1" php -l
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      phpunit
      phpunit -c multisite.xml
    fi
